export default {

    my_account: 'My Account',
    login: 'Login',
    logout: 'Logout',
    online_licence_service: 'Online Licence Service',
    services: 'Services',
    application_instructions: 'Application Instructions',
    application_overview: 'Application Overview',
    application_demo: 'Application Demo',
    application_procedures: 'Application Procedures',
    application_guideline: 'Application Guideline',
    application_form: 'Application Form',
    application_policy: 'Application Policy',
    infoApplicant: 'Information of Applicant',
    faq: {
        title: 'FAQ',
        digital_certificates_and_authentication: 'Diuigital Certificates and Authentication',
        d_title_1: 'What is a digital certificate?',
        d_content_1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        d_title_2: 'Which types of digital certificates do online licence services support?',
        d_content_2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        d_title_3: 'What is the Hongkong Post e-Cert (Personal) for the Smart ID Card? Where can I get more information about it?',
        d_content_3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        d_title_4: 'I am using Windows Vista and Internet Explorer to access an online service that requires user authentication. During user authentication, the screen displays security warnings - "Windows needs your permission to continue" and "A website wants to open web content using this program on your computer". What should I do?',
        d_content_4: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        d_title_5: 'When I tried to use my Digi-Sign Personal ID-Cert to sign an online licence service, I got an error message saying that the certificate could not be found. What should I do?',
        d_content_5: 'The problem probably occurs after the password of the certificate has been changed. If you encounter this problem, please import the certificate into Internet Explorer or Firefox and export a backup copy. You should be able to use the backup copy to login to the online service. Please refer to the ( <a href="http://www.dg-sign.com/eng/frame_service.htm" target="_blank">http://www.dg-sign.com/eng/frame_service.htm</a> ) in Digi-Sign website on how to import and export the ID-Cert.',
    },

    licensing_offices: 'Licensing Offices',
    hong_kong_island_and_outlying_islands: 'Hong Kong Island and Outlying Islands',
    kowloon: 'Kowloon',
    new_territories: 'New Territories',

    disclaimer: 'Disclaimer',
    privacy_statement: 'Privacy Statement',
    food_and_environmental_hygiene_department: 'Food and Environmental Hygiene Department',

    landing: {
        title: 'Liquor / Club Liquor Licence',
        step_1: {
            title: 'Please select service',
        },
        step_2: {
            title: 'Application for',
        },
        step_3: {
            title: 'Form Type',
            reminder: 'Reminder: New Application for Nomination of Reserve Licensee can only be applied with application for new issue/ renewal/ transfer of liquor licence/ club liquor licence. You may fill in the Authorisation form after the nomination has been approved.',
        }
    },

    application_progress: 'Application Progress',
    terms_and_conditions: 'Terms and Conditions',
    save_draft: 'Save Draft',
    save_and_next: 'Save and Next',
    information_relating_to_the_premises: 'Information Relating to the Premises',
    information_relating_to_management: 'Information Relating to Management',
    mode_of_operation: 'Mode of Operation',
    upload_document: 'Upload Document',
    identity: 'Identity Authentication',
    basic_information: 'Basic Information',
    confirmation: 'Confirmation of Application',
    your_submitted: 'Your Application is submitted',
    application_submitted: 'Application Submitted',
    department_feedback: 'Department Feedback',
    documents_verified: 'Documents Verified',
    seek_approval: 'Seek Approval',
    licence_ready: 'Licence Ready',
    licence_issued: 'Licence Issued',
    proceed_to_payment: ' * Proceed to payment',

    applications: 'Applications',
    renewal: 'Renewal',
    follow_up: 'Follow Up',

    new_licence: 'New Licence',
    licence_transfer: 'Licence Transfer',
    application_to_nomination_of_reserve_licensee: 'Application to Nomination of Reserve Licensee',
    temporary_absence: 'Temporary Absence',
    licence_amendment: 'Licence Amendment',
    change_information: 'Change Information (renaming of licensee name or building)',

    liquor_licence: 'Liquor Licence',
    club_liquor_licence: 'Club Liquor Licence',
    nomination_of_reserve_licensee: 'Nomination of Reserve Licensee',
    application_for_authorisation_of_a_nominated_reserve_licensee: 'Application for Authorisation of a Nominated Reserve Licensee',
    declaration_of_the_nominated_reserved_licensee: 'Declaration of the Nominated Reserved Licensee',

    apply: 'Apply',

    reminder_1:'Reminder: New Application for Nomination of Reserve Licensee can only be applied with application for new issue/ renewal/ transfer of liquor licence/ club liquor licence.',
    reminder_2: 'Reminder: You may fill in the Authorisation form after the nomination has been approved.',

    application_for_new_issue_of_a_liquor_licence: 'Application for New Issue of a Liquor Licence',
    shop_sign: 'Shop Sign',
    chinese: 'Chinese',
    english: 'English',
    address: 'Address',
    tips: 'Tips',
    address_note: 'If you have a restaurant licence, the address here shall be the same as that on the restaurant licence. By entering the restaurant licence no. to fill the related information.',
    address_note1: 'Copy information from restaurant licence',
    a_chinese: 'a. Chinese',
    b_english: 'b. English',
    contact: 'Contact',
    tel_no:'Tel no.',
    fax_no:'Fax no.',
    size:'Size of Premises (by reference to floor area inside the premises)',
    premises:'Premises Details',
    br_number: 'a. Business Registration No. of the premises',
    br_number_2: 'b. If the premises is run by a company',
    q5bi: 'Name of company',
    q5b2:'Business Registration No. of the company',
    q5b3:'Company No. (if available)',
    info_rel_rest_lic: 'B. Information Relating to Restaurant Licence',
    q6:'The type of restaurant licence issued/ being applied for the premises under application for liquor licence?',
    q6a: 'The type of restaurant licence',
    q6a1:'Light Refreshment Restaurant Licence',
    q6a2:'General Restaurant Licence',
    q6a3:'Marine Restaurant Licence',
    q6b:'The restaurant licence issued/ being applied',
    q6b1: 'Issued with Licence',
    q6b1_1:'Full Licence',
    q6b1_2:'Provisional Licence',
    q6b1_3:'Restaurant Licence Number',
    q6b2_1:'File Ref. of Restaurant Licence Application',
    q6b2_2:'File Ref.',
    q6b2:'Being Applied',
    q6b3:'Not under application for or covered by a Restaurant Licence or a Certificate of Compliance issued by the Home Affairs Department',
    q6b31:'(Please complete Annex I and submit together with the required documents.)',
    info_rel_to_the_building:'C. Information Relating to The Building',
    q7:'What is the approved use of the building in which the premises are located?',
    q7a:'Mixed Residential and Commercial Uses',
    q7b:'Wholly Commercial Use',
    q7c: 'Other use, please give details',
    q7c1:'File Ref.',
    q8:'The premises have',
    q8a:'Independent access',
    q8b:'Shared access with the other portion of the building',
    profile:{
        profile: 'Profile',
        user: 'User ：  ',
        instruction: 'Please update your personal profile. The particulars will be used as default in the electronic forms.',
        personal_profile: 'Personal Profile',
        name_eng: 'Name (English)',
        premises: 'Premises for liquor licence',
        tel: 'Tel No. (Mobile)',
        email: 'Email',
        address: 'Correspondence address'
    },
    new_submitted:{
        new_issue: 'Application for New Issue of a Liquor Licence',
        submitted: 'Your Application is submitted',
        ref: 'Your application reference number is ',
        circumstances: '. Under normal circumstances the whole confirmation will take around 8-10 weeks. You need to proceed to payment when licence is ready. We will keep you updated if you have any document missing for processing the application.',
        my_account: 'Go to My Account',
    },

overview:{
        title_1: 'Overview of the Liquor / Club Liquor Licence Application',
        a_1: 'Under the Dutiable Commodities (Liquor) Regulations (Cap.109B), any person seeking a liquor licence or club liquor licence, shall make application in writing to the Board in accordance with the form determined by the Liquor Licensing Board (LLB) - a statutory body established under Cap.109B who is responsible for the licensing of premises used for the sale or supply of liquor for consumption on the premises.',
        a_2: 'LLB has given consents to accept applications and documents in form of electronic records. With effect from 1 August 2010, you may submit the application to the Licensing Offices of Food and Environmental Hygiene Department (FEHD) by filling the appropriate forms, attaching relevant information through electronic files and signing the forms digitally through the system.',
        a_2a: 'By Amendment to the Dutiable Commodities (Liquor) Regulation in 2015, it is a requirement to sign on the electronic form with a digital signature, or a password assigned or approved by LLB. LLB will accept electronic submission of applications for the issue, renewal, transfer or amendment of liquor licences if accompanied by either a password assigned or approved by the LLB or by a digital signature and this will be rolled out in two phases. ',
        a_2b: 'Starting from July 2016, you may submit application for renewal or amendment of a liquor licence or club liquor licence online by a password assigned or approved by LLB other than a digital signature ',
        a_2c: 'in the first phase. In the second phase, application for new issue, transfer and other type of applications of a liquor licence or club liquor licence are covered in October 2016.',
        
        title_2: 'General Requirements',
        b_1: 'Online Licence Services on the Liquor Licence Processing System (LLPS) are provided under the provision of the Electronic Transaction Ordinance (ETO). You must have an account in the LLPS before being able to submit electronic forms. To ensure successful submission of electronic application, please note the following:',
        b_2: 'This service is designed to be used by Adobe Reader 9.2 or above, and Microsoft Internet Explorer version 6 (or above) on Windows platform (Microsoft Windows 2000, Microsoft Windows XP, Microsoft Windows Vista, Windows 7) or Mozilla Firefox version 3 (or above) on Linux platform, Mac OS X platform, and Windows platform (Microsoft Windows 2000, Microsoft Windows XP, Microsoft Windows Vista, Windows 7).',
        b_3: 'Browser configurations including Javascript, Cookies, 28-bit SSL, and Java (for payment through internet PPS) must be enabled. For IE6.0 users, if you are going to settle payment through Internet PPS or with a HSBC or Hang Seng VISA credit card, you must change the default privacy settings of your browser in order to accept cookies from the relevant website. Otherwise you will not be able to complete the transaction.',
        b_4: 'If you are going to settle payment by a Visa credit card, you must register the "Verified by Visa" service with your card issuing bank. Otherwise you may not be able to complete the transaction. Some Visa card and MasterCard issuers do not support online payment, please check with your credit card issuers to ascertain if they support online payment.',
        b_5: "To ensure a smooth payment process, please check if your computer's hardware, software and internet connection settings meet the following requirements of the system",
        b_6a: 'Operation System: Windows XP',
        b_6b: 'Browser: Microsoft Internet Explorer Browser (7.0)',
        b_6c: 'Java Enabled: Yes',
        b_6d: 'Java Vendor and Version: Sun Microsystems 1.6.0_11',
        b_6e: 'JavaScript Enabled: Yes',
        b_6f: 'Cookie Enabled: Yes',
        b_7: 'For correct display and input of Chinese Characters in Adobe Reader, Traditional Chinese version is recommended. Chinese Traditional Font Packs should be installed for non-Chinese version ->',
        b_8: 'For correct display of Chinese Characters in browsers, the computer must be able to display the Big-5 or ISO10646 character set with "the Hong Kong SupplSteps to Submit Application character set can be downloaded at －＞',
        b_9: 'You must have a valid digital certificate issued by the Hong Kong Post Office or any Certificate Authority recognized by the HKSAR Government.',
        b_10: 'File attachments must not be larger than 5MB in total for each submission and must be compiled to the acceptable format.',

        title_3: 'Acceptable File Formats',
        c_1: 'The electronic files to be submitted should be in any of the following formats:',
        c_2: 'Plain text (TXT), which is a document format in which a sequence of characters and the words they form are encoded into computer-readable format using various types of language coding schemes. Most of the word processing software in the market allow users to save their document as plain text. Please note that when a document is saved as plain text, special effects such as font size, boldface, italics, underline, etc. will be lost.',
        c_3: 'Microsoft Rich Text Format, which is promulgated by Microsoft Corporation. It is supported by the majority of word processing software in the market and can be used to submit files with formatting retained. To do so, choose "Save As" function and choose "Rich Text Format (RTF)" as the document type. Many word processing software not developed by the Microsoft Corporation also allow the saving of documents in RTF format. For the avoidance of doubt, documents in Microsoft Word format (with extension .doc) are not acceptable.',
        c_4: 'Hypertext Mark Up Language Format. HTML is a document format promulgated by the World Wide Web Consortium for the content on web pages. Many word processing software in the market allow users to save their documents in HTML format. For the avoidance of doubt, documents with embedded Visual Basic code, Flash, Java scripts, or other embedded programming codes are not acceptable.',
        c_5: 'Adobe Portable Document Format (compatible to Acrobat version 5 or above) promulgated by the Adobe Systems Incorporated. Tools can be used to convert textual documents into PDF format.',
        c_6: 'Encapsulated PostScript Files (EPSF).',
        c_7: 'Portable Network Graphics (PNG).',
        c_8: 'Tag Image File Format (TIFF) promulgated by Adobe Systems Incorporated.',
        c_9: 'Graphic Interchange File Format (GIF) promulgated by CompuServe Incorporated.',
        c_10: 'Windows BitMaps (BMP).',
        c_11: 'Joint Photographic Experts Group (JPEG) promulgated by the International Organisation for Standardisation (ISO) and the International Telecommunication Union (ITU).',
        c_12: 'In respect of Computer Aided Design (CAD) drawings, an open standard - Autodesk Drawing Exchange Format (DXF) promulgated by Autodesk, Inc. is acceptable.',
    },
    videoDemo:{
        title: 'Video Demo',
        content_1: 'Please click the video below to view the Online Help video for illustration of the steps for checking information at the Online Licence Services.',
        content_2: 'PDF Demo',
        content_3: 'Click to view the pdf demo',
        content_4: 'Application for new issue of a liquor licence',
        content_5: 'Application for renewal of a liquor licence',
        content_6: 'Application for transfer of a liquor licence',
    },
    applicationProcedure:{
        title_1: 'Application Procedures',
        a_1: '1. Document Preparation',
        a_2: 'Liquor Licence',
        a_3: 'Each applicant is required to complete one copy of an application form and return it with the following documents:',
        a_4: "a copy of the applicant's HKID Card;",
        a_5: 'a copy of each of the business registration certificate of the restaurant and company (if the establishment under application is a limited company);',
        a_6: '2 recent photographs (35mm x 40mm) of the applicant ;',
        a_7: '3 copies of a plan showing the layout of the premises with clear indication of the area used for dancing (for applications with dancing endorsement only);',
        a_8: 'a copy of the certificate of incorporation if the owner of the establishment under application is a corporation;',
        a_9: 'a copy of the full or provisional general/light refreshment/marine restaurant licence, if available,',
        a_10: 'a copy of the business registration certificate bearing the new shop sign (for change of shop sign of the establishment only);',
        a_11: 'a copy of the amended business registration certificate in respect of the premises under application (for amendment of size of licensed premises); and',
        a_12: '3 copies of a plan showing the layout of the premises with clear indication of the area included/deleted (for amendment of size of licensed premises).',
        a_13: 'For liquor licence application in respect of the premises not under application for or covered by Restaurant Licence or Certificate of Compliance, please submit the following documents:',
        a_14: '5 copies of identical proposed layout plans are required to show the layout of the premises including the portion for sale or supply of liquor and for consumption of liquor on the premises. Such plans should be drawn to scale (of not less than 1:100) in metric units;',
        a_15: '3 copies of identical proposed ventilating system layout plans together with the Supplier Certificate are required if the ventilating system is installed in the premises. Such plans should be drawn to scale (of not less than 1:100) in metric units; and',
        a_16: '3 copies of identical location maps drawn to scale of 1:1000, in metric units, are required to clearly indicate the location of the premises.',

        title_2: 'Club Liquor Licence',
        b_1: 'Club Liquor Licence',
        b_2a: 'Application for a club liquor licence must be made by the secretary of the club. The licence shall be issued to the secretary of the club or a person nominated by the club.',
        b_2b: 'Each applicant is required to complete one copy of an application form and return it with the following documents:',
        b_3: 'If the club is established under the Societies Ordinance (Cap. 151) -',
        b_4: 'a letter from the Societies Officer;',
        b_5: "a copy of the proposed licence holder's HKID Card;",
        b_6: '2 recent photographs (35mm x 40mm) of the proposed licence holder;',
        b_7: '3 copies of the certified true copy of the club rules;',
        b_8: 'a copy of the minutes regarding the appointment of the club liquor licence holder;',
        b_9: '2 copies of a layout plan of the club;',
        b_10: "a copy of the documents showing the club's admission procedure for members, membership application form and membership card; and",
        b_11: 'a copy of the Certificate of Compliance issued under the Clubs (Safety of Premises) Ordinance (Cap. 376) issued by the Home Affairs Department, if available.',
        b_12: 'If the club is a limited company incorporated under the Companies Ordinance (Cap. 32)-',
        b_13: '3 copies of the Memorandum and Articles of Association of the club;',
        b_14: 'a certified true copy of the Certificate of Incorporation of the club;',
        b_15: 'a certified true copy of the latest Annual Return of the club;',
        b_16: 'a certified true copy of the resolution of the board of directors approving the appointment of the applicant to be the licensee if the application is approved and the adoption of the club rules;',
        b_17: 'a copy of each the business registration certificate of the club and company;',
        b_18: "a copy of the proposed licence holder's HKID Card;",
        b_19: '2 recent photographs (35mm x 40mm) of the proposed licence holder;',
        b_20: '3 copies of the certified true copy of the club rules;',
        b_21: '2 copies of a layout plan of the club;',
        b_22: "a copy of documents showing the club's admission procedure for members, membership application form and membership card; and",
        b_23: 'a copy of the Certificate of Compliance issued under the Clubs (Safety of Premises) Ordinance (Cap. 376) issued by the Home Affairs Department, if available.',
        b_24: 'If the club is a proprietary club operated by a limited company incorporated under the Companies Ordinance (Cap. 32) -',
        b_25: '3 copies of the Certificate of Incorporation of the limited company, of which one is certified true by the Company Registry;',
        b_26: '3 copies of the Memorandum and Articles of Association of the limited company;',
        b_27: 'a certified true copy of the latest Annual Return of the limited company;',
        b_28: 'a certified true copy of the resolution of the board of directors approving the establishment of the club specifying its name and address, the appointment of the applicant to be the licensee if the application is approved and the adoption of the club rules;',
        b_29: 'a copy of the business registration certificate of the limited company;',
        b_30: 'a copy of the branch registration certificate of the club;',
        b_31: '3 copies of the certified true copy of the club rules;',
        b_32: '2 recent photographs (35mm x 40mm) of the proposed licence holder;',
        b_33: "a copy of the proposed licence holder's HKID Card;",
        b_34: '2 copies of a layout plan of the club;',
        b_35: "a copy of documents showing the club's admission procedure for members, membership application form and membership card; and",
        b_36: 'a copy of the Certificate of Compliance issued under the Clubs (Safety of Premises) Ordinance (Cap. 376) issued by the Home Affairs Department, if available.',

        title_3: '2. Processing of the Application',
        c_1: 'New Issue of Licence',
        c_2: 'After submission of an application, applicant may be required to attend an interview to be arranged by the Secretary, Liquor Licensing Board for the purpose of further verifying the information provided in the application form and other matters relating to the application.',
        c_3: 'All applications are referred to the Commissioner of Police and the District Officer concerned for comments. For club liquor licence application, the application is referred to the Office of the Licensing Authority, Home Affairs Department for comments if an application for a Certificate of Compliance in respect of the club is being processed by the Office.',
        c_4: "Public opinion is also sought and this is done by placing an advertisement, at the applicant's expense, in three newspapers (other than in the classified advertisement column) in accordance with the requirements and standard format provided by the licensing offices. Upon receipt of the application, Liquor Licensing Board will post the notice on application for Liquor / Club Liquor Licence on its website.",
        c_5: "For liquor licence application in respect of the premises not under application for or covered by Restaurant Licence or Certificate of Compliance",
        c_6: "In addition to consulting the Hong Kong Police Force and District Office of Home Affairs Department, the application will be referred to Planning Department, Fire Services Department, Buildings Department/ Housing Department/ Architectural Services Department and Food and Environmental Hygiene Department, etc. for comment.",
        c_7: "Except for premises in Government properties or Housing Authority properties, certification made by recognised professional(s) (i.e. authorized persons/ structural engineers registered under Section 3 of the Buildings Ordinance (Cap.123)) certifying that the premises are free of unauthorized building works shall be submitted (in person or by mail) to Liquor Licensing Board in prescribed form (FEHB 267) as in accordance with the corresponding guidelines, where appropriate, listed as follows:",
        c_8: '"Certification of Food Business Premises Free of Unauthorized Building Works - Guidelines for Authorized Persons and Registered Structural Engineers" issued by the Director of Buildings"',
        c_9: '"Certification of Food Business Premises Free of Unauthorized Building Works - Guidelines for Authorized Persons and Registered Structural Engineers (applicable to the properties divested to The Link Management Limited)" issued by the Independent Checking Unit of Housing Department',
        c_10: 'If a ventilating system is installed, the standard of ventilation shall be a supply of not less than 17 cubic metres of outside air per hour for each person accommodated on the premises.',
        c_11: 'It takes longer processing time than normal liquor licence applications.',

        c_12a: 'Renewal & Amendment(s) of Licence',
        c_12b: 'Application for renewal of a liquor licence or club liquor licence are required to be submitted to the respective Licensing Office not more than 4 months and not less than 3 months before the licence is due for renewal. Where the period of liquor licence or club liquor licence is 3 months, the application for renewal of the licence is required to be submitted not less than 2 months before the licence is due to renewal.',
        c_12c: '',
        c_12d: '',        
        c_13: 'Application for amendment(s) of a liquor licence or club liquor licence is made usually for the following purposes-',
        c_14: 'to change the shop sign of the licensed premises;',
        c_15: 'to seek endorsement on the licence to operate a bar, dancing hall, etc.;',
        c_16: 'extension of the licensed premises;',
        c_17: '(Only applicable to Hotels) Addition of a New Portion, which is not under Application for or covered by a Restaurant Licence or a Certificate of Compliance issued by the Home Affairs Department, to Licensed Premises; or',
        c_18: 'any other specific reasons.',
        c_19: 'The process of both applications is similar to that of new issue of liquor licences.',
        c_20: 'For liquor licence application in respect of the premises not under application for or covered by Restaurant Licence or Certificate of Compliance.',
        c_21: 'In case of renewal of liquor licence, the Liquor Licensing Board will consult Fire Services Department on the compliance of fire safety requirements including submission of Certificate of Fire Service Installations and Equipment (F.S.251) and Annual Inspection Certificate of the premises.',
        c_22: 'In case of amendment of change of size of the premises, the application must be accompanied by 4 copies of identical layout plans and/or 3 copies of ventilation plans showing the proposed alteration(s) and/or addition(s) to the premises. Proposed layout/ventilation plan must be drawn in metric unit and in scale commonly used of not less than 1:100. The application will be referred to the Hong Kong Police Force, District Office of Home Affairs Department, Planning Department, Fire Services Department, Buildings Department/ Housing Department/ Architectural Services Department etc. and government departments concerned for comment.',
        c_23: 'It will take longer processing time than normal liquor licence applications.',
        
        c_24: 'Transfer of Liquor Licence',
        c_25: 'The transferee applicant is required to complete an application form and return it to the Licensing Office together with the documents previously mentioned above.',
        c_26: 'The process of application is also similar to that of new issue of liquor licences.',
        c_27: 'For liquor licence application in respect of the premises not under application for or covered by Restaurant Licence or Certificate of Compliance',
        c_28: 'For transfer of liquor licence, except for premises in Government properties or Housing Authority properties, the transferee of an existing liquor licence is required to submit (in person or by mail) certification made by recognised professional(s) (i.e. authorized persons/ structural engineers registered under Section 3 of the Buildings Ordinance (Cap.123)) certifying that the premises are free of unauthorized building works to Liquor Licensing Board in prescribed form (FEHB 267) as in accordance with the corresponding guidelines listed in the application for new issue of liquor licence in respect of the premises.',
        c_29: 'It will take longer processing time than normal liquor licence applications.',

        c_30: 'Application Procedures under Reserve Licensee Mechanism',
        c_31: 'The Mechanism comprises of vetting application for nomination of reserve licensee and application of authorization of reserve licensee.',
        c_32: 'A person to be nominated as a reserve licensee should meet the "fit and proper person" criterion and not be a licence holder or reserve licensee of other liquor licensed premises.',
        c_33a: "The maximum period for authorization of the reserve licensee during the absence of the liquor licensee is capped at 25% of the number of days of the validity period of the liquor licence, and for a liquor licence with a validity period of more than one year, each period must not exceed 90 days (and the aggregate periods must not exceed 90 days within any 12 consecutive months in the validity period of the licence)",
        c_33b: 'The existing licensee’s temporary resignation mechanism is still in use.',
        c_34: 'Application for Nomination of Reserve Licensee',
        c_35a: 'An application for nomination of reserve licensee has to be submitted together with application for new issue / renewal / transfer of liquor licence. ',
        c_35b: 'The application form for nomination of reserve licensee is attached at the Annex I/II of application form for new issue (FEHB 106/107), renewal (FEHB 106A/107A) and transfer (106B/107B) of liquor/club liquor licence. It is optional to apply for nomination of reserve licensee. An individual application for nomination of reserve licensee will not be processed.',
        c_36: 'All applications for nomination of reserve licensee are referred to the Police for comment. After seeking comments from the Police, the Secretary of Liquor Licensing Board will, in general, consider the application in about 8 weeks upon the approval to new issue / renewal/ transfer applications.',
        c_37: 'Not more than one application for nomination of reserve licensee should be submitted during the validity period of liquor licence except transfer application and in case of refusal of the first nomination application during the validity period of liquor licence.',
        c_38: 'Application for authorization of reserve licensee upon sudden departure of Licensee',
        c_39: "Should there be a sudden departure of licensee, the licensee /owner / proprietor of liquor selling business is required to submit the following documents for authorization of the nominated reserve licensee to take over the role of the licensee at least 7 working days before the licensee's departure:",
        c_40: 'an application for authorization of reserve licensee (FEHB 266A); and',
        c_41: "a declaration of reserve licensee's (FEHB 266B).",
        c_42: '[Note: In parallel, the concerned owner / proprietor should submit application of new issue / transfer of liquor licence as appropriate.]',
        c_43: "Subject to the reserve licensee's self-declaration of not being an existing liquor licence holder and no change in criminal record subsequent to approval for nomination, the Secretary of Liquor Licensing Board will consider to grant approval-in-principle to the authorization of reserve licensee in 2 to 4 working days. At the same time, the application with the declaration will be referred to the Police for comment.",
        c_44: 'Upon receiving the comments of the Police, the Secretary will consider formally approve the authorization or revoke the approval-in-principle for authorization. The authorization will only take effect upon payment of a prescribed fee.',

        c_45: 'Application Procedures for Temporary absence of Licensee',
        c_46: 'In case of illness or temporary absence of the licensee, the licensee is required to submit an application for permission to authorise a person to manage the licensed premises at least 7 working days before the start date of temporary absence if leave period is not more than 30 days and 15 working days before the start date of temporary absence if leave period is more than 30 days. The application should be submitted to the respective Liquor Licensing Office together with the following documents:',
        c_47: 'a recent photograph of the authorized person;',
        c_48: "a copy of the authorized person's HKID card or other identification document; and",
        c_49: 'a copy of the leave approval letter from the company/ employer if the applied period is more than 10 days.',
        c_50: 'With a reserve licensee in place, the application form can be submitted at least 7 working days before start date of temporary absence.',
        c_51: 'The maximum period for authorization of a person to manage the licensed premises during temporary absence of the licensee is the same as that of reserve licensee mechanism.',

        title_4: '3. Licensing Conditions',
        c_52: 'Liquor Licence',
        c_53: 'No disorder shall be permitted on the premises.',
        c_54: 'No person shall be allowed to become drunk on the premises, nor shall liquor be supplied to any person who is drunk.',
        c_55: 'No games of chance shall be played on the premises.',
        c_56: 'The licensee shall personally supervise the premises.',
        c_57: 'The licensee shall display a warning notice at a conspicuous place inside the premises containing the words "NO LIQUOR FOR PERSON UNDER THE AGE OF 18". In the said notice, the size of each Chinese character shall not be less than 3 cm (height) x 3 cm (width) and the size of each English letter shall not be less than 2 cm (height) x 2 cm (width).',
        c_58: 'The licensee shall exhibit and keep exhibited a notice denoting its licensed status provided by the Board at the main entrance of the premises.',
        c_59: 'The licensee shall not permit any person to occupy or use any portion of the premises for any immoral or illegal purpose.',
        c_60: 'The licensee shall not permit any common prostitutes or reputed thieves to assemble or remain on the premises.',
        c_61: 'The licensee shall not permit drunkenness, or violence, quarrel or other disorderly conduct on the premises and shall not permit persons of known bad character to assemble and remain on the premises.',
        c_62: 'The name of any liquor for which a standard of quality is prescribed by regulations shall be clearly marked on the container in or from which the liquor is supplied to any customers.',
        c_63: 'No bar business shall be operated on the premises, except with the permission of the Board endorsed herein.',
        c_64: 'No dancing shall be permitted on the premises, except with the permission of the Board endorsed herein.',
        c_65: 'Toilets shall be maintained in a state of cleanliness and good repair for the use of customers.',
        c_66: 'Except exempted by the Board, the licensed premises shall be concurrently covered by a valid restaurant licence issued by the Director of Food and Environmental Hygiene.',

        c_67: 'Club Liquor Licence',
        c_68: 'No disorder shall be permitted on the club premises.',
        c_69: 'No person shall be allowed to become drunk on the club premises, nor shall liquor be supplied to any person who is drunk.',
        c_70: 'The licensee shall personally supervise the club premises.',
        c_71: 'The licensee shall display a warning notice at a conspicuous place inside the club premises containing the words "NO LIQUOR FOR PERSON UNDER AGE 18". In the said notice, the size of each Chinese character shall not be less than 3 cm (height) x 3 cm (width) and the size of each English letter shall not be less than 2 cm (height) x 2 cm (width).',
        c_72: 'The licensee shall exhibit and keep exhibited a notice denoting its licensed status provided by the Board at the main entrance of the club premises.',
        c_73: 'The licensee shall not permit any person to occupy or use any portion of the club premises for any immoral or illegal purpose.',
        c_74: 'The licensee shall not permit any common prostitutes or reputed thieves to assemble or remain on the club premises.',
        c_75: 'The licensee shall not permit drunkenness, or violence, quarrel or other disorderly conduct on the club premises and shall not permit persons of known bad character to assemble and remain on the club premises.',
        c_76: 'Toilets shall be maintained in a state of cleanliness and good repair for the use of members.',
        c_77: 'Except exempted by the Board, the club liquor licence shall be concurrently covered by a valid Certificate of Compliance issued by the Secretary for Home Affairs.',
    },
    assessmentGuideline:{
        title_1: 'Guidelines on assessing Liquor Licence Applications',
        content_1a: 'To enhance transparency as well as to help the trade and the public better understand the factors that are taken into account by the Liquor Licensing Board (LLB) when assessing liquor licence applications, the LLB has prepared a set of guidelines that capture the criteria used in vetting liquor licence applications.',
        content_1b: ' The Guidelines on Assessing Liquor Licence Applications ',
        content_1c: '(the Guidelines) do not carry the force of law and, as such, are not meant to bind LLB members. When considering the merits of individual applications, it is incumbent upon the LLB to give a full and fair hearing to each case in accordance with the requirements under the legislation. The LLB will keep the Guidelines under review and will update them as necessary.',
        content_2a: 'The factors set out in the Guidelines have been developed from the three criteria stipulated under Section 17(2) of the Dutiable Commodities (Liquor) Regulations (Cap. 109B), namely whether the applicant is a fit and proper person to hold the licence, whether the premises are suitable for the sale of liquor, and whether the grant of the licence is contrary to the public interest. In general, the criteria for assessing liquor licence applications are applicable to all types of liquor-licensed premises. Bearing in mind the fact that "upstairs bars"',
        content_2b: ' are relatively more prone to attract public concerns, we have, under each of the three major criteria in the Guidelines, set out the factors that the LLB would specifically take into account when vetting liquor licence applications from "upstairs bars".',
        content_3: 'Most of the criteria cited in the Guidelines have all along been adopted by the LLB in assessing liquor licence applications. When preparing the Guidelines, the LLB has also taken the opportunity to review the effectiveness of the existing licensing conditions and proposed the inclusion of new conditions as appropriate, in the interest of ensuring that the licensing mechanism remains appropriate and relevant in present-day circumstances.',
        content_4: 'The new licensing conditions will take effect in future by phases. A brief description of these conditions and their respective inception dates are set out below.',
        content_5: 'New Licensing conditions for "upstairs bars"',
        content_6a: '"Seminar on Liquor Licensing"',
        content_6b: 'With effect from ',
        content_6c: '1 December 2013, ',
        content_6d: 'upon receipt of (i) applications for new issue or transfer of liquor licence; or (ii) applications for renewal of liquor licence, the LLB will impose an additional licensing condition requiring the licensee to attend the "Seminar on Liquor Licensing" (the Seminar) within the licence period. The Seminar will cover the topics of fire safety, public order and environmental hygiene in a manner sensitive to the management needs of "upstairs bars". In general, each licensee is required to attend the Seminar once.',
        content_7a: 'Capacity limit: safety margin',
        content_7b: 'The LLB may, having regard to the actual circumstances and the advice of the departments concerned, consider imposing a safety margin on the capacity limit for "upstairs bars" that is more stringent, say 90% of the capacity limit that is otherwise applicable, and prescribing it as one of the licensing conditions.',
        content_7c: 'The new requirement will come into effect on ',
        content_7d: '1 June 2014. ',
        content_7e: 'Upon receipt of applications for new issue of liquor licence on or after 1 June 2014, the LLB will consider adopting a 90% safety margin on the capacity limit as a licensing condition. For licences that already exist on or before 31 May 2014, the LLB will, when dealing with the renewal application immediately subsequent to the next renewal, consider adopting the 90% safety margin on the capacity limit as a licensing condition. This is to give ample grace period.',
        content_8: 'New Licensing conditions for all liquor-licenced premises',
        content_9a: 'More stringent noise abatement measures',
        content_9b: 'The LLB will consider requiring liquor-licensed premises to take additional noise insulation measures in cases with serious noise problems. When considering doing so, the LLB will take into account the actual circumstances of individual premises, such as the practicability of installing double-glazed windows or double doors at the entrance on such premises as well as the availability of any other more appropriate acoustic insulation materials.',
        content_9c: 'This new requirement will come into effect on ',
        content_9d: '1 June 2014. ',
        content_9e: 'Upon receipt of applications for new issue or renewal of liquor licence on or after 1 June 2014, the LLB will consider imposing licensing conditions regarding noise insulation which are more stringent than the existing ones in cases with serious noise problems.',
        content_10: 'For enquiries, please contact the LLB Secretariat or the respective Liquor Licensing Offices.',
        content_11a: 'Liquor Licensing Board',
        content_11b: '1 December 2013',
        content_12a: 'The term "upstairs bars" refers to liquor-licensed premises which operate as bars with the sale and consumption of liquor on the premises being the main line of business and which are not located at the street level. These premises are mostly situated in office buildings or domestic/commercial buildings. Due to their special physical environment and the relatively greater difficulties inherent in taking enforcement actions and conducting inspections in respect of fire safety, noise, environmental hygiene and public nuisance, etc., they are prone to attract public concerns and draw complaints from the neighbourhood nearby. In general, for liquor-licensed premises that are located in shopping centres, hotels or buildings specifically designed for entertainment businesses, we do not put them under the "upstairs bars" category.',
        content_12b: 'Individual holders of liquor licences who have doubts on whether their premises fall under the category of "upstairs bars", or any person who wishes to rent or buy a building unit for operating bar business and wants to know whether it will be classified as an "upstairs bar", may make enquiries with the LLB Secretariat or the respective Liquor Licensing Offices.',
    },
    downloadForm:{
        title_1: 'Download Application Form',
        content_1: 'FEHB 106',
        content_2: 'Application for New Issue of a Liquor Licence',
        content_3: 'FEHB 106A',
        content_4: 'Application for Renewal of a Liquor Licence',
        content_5: 'FEHB 106B',
        content_6: 'Application for Transfer of a Liquor Licence',
        content_7: 'FEHB 106C',
        content_8: 'Application for Amendment of a Liquor Licence',
        content_9a: 'Liquor Licence',
        content_9b: 'Club Liquor Licence',
        content_10: 'FEHB 107',
        content_11: 'Application for New Issue of a Club Liquor Licence',
        content_12: 'FEHB 107A',
        content_13: 'Application for Renewal of a Club Liquor Licence',
        content_14: 'FEHB 107B',
        content_15: 'Application for Transfer of a Club Liquor Licence',
        content_16: 'FEHB 107C',
        content_17: 'Application for Amendment of a Club Liquor Licence',
        content_18: 'Temporary Absence',
        content_19: 'FEHB 239',
        content_20: 'Application for Temporary Absence of Liquor Licensee for a Period Not Exceeding 25% of the Number of Days of the Validity Period of the Licence',
        content_21: 'FEHB 266A',
        content_22: 'Application for Authorisation of a Nominated Reserve Licensee',
        content_23: 'FEHB 266B',
        content_24: 'Declaration of the Nominated Reserve Licensee',
    },
    accountPolicy:{
        title_1: 'Account Policy',
        content_1: 'The Liquor Licensing Board (LLB), a statutory body established under the Dutiable Commodities (Liquor) Regulations who is responsible for the licensing of premises used for the sale or supply of liquor for consumption on the premises, has given consents to accept applications and documents in form of electronic records.',
        content_2: 'For security reason, personalised on-line services are provided to users with accounts only. If you do not have an account, please provide your personal information and complete the registration process online to request for an user account. Please note that this account is only for online licence services related to liquor / club liquor licences.',
        content_3: 'For any change of personal particulars afterwards, you shall amend your account profile after successful login to the system.',
        content_4: 'Applicant of new licence or licence transfer',
        content_5: 'You need to provide your name, location of premises, phone number, correspondence address and e-mail address to create an account online. You have to download the Password Request Form and sign on it. Upon receiving your signed Password Request Form, a password for your user account will be assigned to you emailed to your correspondence address. You can use your account to:',
        content_6: 'Submit new licence or licence transfer application;',
        content_7: 'Check status of submitted application;',
        content_8: 'Read messages from the Licensing Office; and',
        content_9: 'Make payment (if necessary)',
        content_10: 'Once your application for new licence / licence transfer has been approved, your user account could be used to –',
        content_11: 'Apply for renewal / amendment;',
        content_12: 'Apply for licence copy / temporary absence of licensee / employment of young persons;',
        content_13: 'Notify the Licensing Office the renaming of licensee name or building related to the premises address;',
        content_14: 'Check status of submitted applications;',
        content_15: 'Read messages, if any, from the Licensing Office; and',
        content_16: 'Make payment (if necessary).',
        content_17: 'If you do not yet have an online user account but an application has been submitted to the Licensing Office, a user account will be created for you once the Licensing Office starts to process your application. User name and password for the account will be delivered to you by post to your correspondence address together with the acknowledgement letter.',
        content_18: 'If you do not activate the assigned online user account to submit an application but deliver the application in person or by post to the Licensing Office, a fresh user account will be assigned for you once the Licensing Office starts to process your application. User name and password for the account will be delivered to you by post to your correspondence address together with the acknowledgement letter.',
        content_19: 'Licensee',
        content_20: 'Accounts have been created for existing licensees and letters with user names and passwords assigned or approved by LLB will be delivered to the licence holders in batches by post. You can then use your account to –',
        content_21: 'Apply for renewal / amendment;',
        content_22: 'Apply for licence copy / employment of young persons;',
        content_23: 'Notify the Licensing Office the renaming of licensee name or building related to the premises address;',
        content_24: 'Check status of submitted applications;',
        content_25: 'Read messages, if any, from the Licensing Office; and',
        content_26: 'Make payment (if necessary).',
        content_27: 'If you wish to submit new licence or licence transfer application, you need to provide your name, premises address, phone number, correspondence address and e-mail address to create an account online for making this application.',
        content_28: 'Validity period of user accounts',
        content_29: 'Your user account will be purged automatically under the following circumstances:',
        content_30: 'You do not have any ',
        content_31: 'in-progress ',
        content_32: 'application for new licence / licence transfer (e.g. you have not submitted any application to the Licensing Officer or the application has been refused / withdrawn / abandoned) ',
        content_33: 'and ',
        content_34: 'your account has been inactive for ',
        content_35: 'six months;',
        content_36: 'OR',
        content_37: 'Your liquor licence or club liquor licence is no longer valid (e.g. expired, cancelled, revoked, transferred)',
    },

}


